trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  JAR_NAME: 'tts-backend-1.0.0.jar'

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'

- task: CopyFiles@2
  inputs:
    contents: 'target/$(JAR_NAME)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'